[workspace]
members = [
  "bench",
  "cli",
  "examples",
  "lib/compute",
  "lib/extensions",
  "lib/common",
  "lib/encoding",
  "lib/execution",
  "lib/functions",
  "lib/logical",
  "lib/physical",
  "lib/storage",
  "lib/rdf-fusion",
  "lib/web",
  "lib/wasm",
  "testsuite",
]
resolver = "2"

[workspace.package]
version = "0.2.1"
authors = ["Tobias Schwarzinger <tobias.schwarzinger@tuwien.ac.at>"]
license = "Apache-2.0"
edition = "2024"
rust-version = "1.86"                                                # Minimum Supported Rust Version (Adopt from DataFusion)
repository = "https://codeberg.org/tschwarzinger/rdf-fusion"

[workspace.dependencies]
anyhow = "1.0"
async-trait = "0.1"
async-stream = "0.3"
base16ct = { version = "1.0", features = ["alloc"] }
bytes = "1.12"
chrono = "0.4"
clap = "4.6"
clap_complete = "4.6"
clap_mangen = "0.3"
console-subscriber = "0.5"
csv = "1.4"
futures = "0.3"
itertools = "0.15"
md-5 = "0.11"
object_store = "0.13"
rand = "0.10"
regex = "1.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha1 = "0.11"
sha2 = "0.11"
snmalloc-rs = "0.7"
thiserror = "2.0"
time = "0.3"
tokio-util = { version = "0.7", features = ["io"] }
url = "2.5"
uuid = "1.24"
quick_cache = "0.7"
heed = "0.22"
oneshot = "0.2"

# DataFusion and Related Dependencies (we try to keep them in-sync with DataFusion)
ahash = "0.8"
arrow-string = "58.1"
datafusion = "53.1"
deltalake = { version = "0.32", features = ["datafusion", "datafusion-ext"] }
reqwest = { version = "0.12", features = ["stream"] }
tokio = { version = "1.51", features = ["rt", "sync", "macros"] }

# Logging / Tracing

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }

# Web Dependencies

axum = "0.8"
axum-extra = { version = "0.12", features = ["typed-header"] }
axum-test = "21.0"
console_error_panic_hook = "0.1"
headers = "0.4"
headers-accept = "0.3"
js-sys = "0.3"
mediatype = "0.21"
tower-http = { version = "0.7", features = ["cors", "trace"] }
serde_urlencoded = "0.7"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = "0.3"

# Testing / Benchmarking dependencies

assert_cmd = "2.2"
criterion = { version = "0.8", features = ["async_tokio"] }
insta = { version = "1.48", features = ["filters"] }
prettytable-rs = "0.10"
text-diff = "0.4"
tempfile = "3.27"
tokio-test = "0.4"

# Upstream Oxigraph dependencies
oxttl = "0.2"
oxiri = "0.2"
oxrdf = "0.3"
oxrdfio = { version = "0.2", features = ["async-tokio"] }
sparesults = { version = "0.3", features = ["async-tokio"] }
spargebra = "0.4"

# Internal dependencies
rdf-fusion-compute = { version = "=0.2.1", path = "lib/compute" }
rdf-fusion-extensions = { version = "=0.2.1", path = "lib/extensions" }
rdf-fusion-common = { version = "=0.2.1", path = "lib/common" }
rdf-fusion-encoding = { version = "=0.2.1", path = "lib/encoding" }
rdf-fusion-execution = { version = "=0.2.1", path = "lib/execution" }
rdf-fusion-functions = { version = "=0.2.1", path = "lib/functions" }
rdf-fusion-logical = { version = "=0.2.1", path = "lib/logical" }
rdf-fusion-physical = { version = "=0.2.1", path = "lib/physical" }
rdf-fusion-storage = { version = "=0.2.1", path = "lib/storage" }
rdf-fusion = { version = "=0.2.1", path = "lib/rdf-fusion" }
rdf-fusion-web = { version = "=0.2.1", path = "lib/web" }

[profile.dev]
# TODO: Remove once DF join estimation does not overflow
overflow-checks = false

[profile.test]
# TODO: Remove once DF join estimation does not overflow
overflow-checks = false

# Try to alleviate issues with high memory usage of `wasm-bindgen-test-runner`
[profile.test.package.rdf-fusion-wasm]
debug = false
opt-level = 1

[profile.release]
codegen-units = 1
lto = true
strip = true      # Eliminate debug information to minimize binary size

# the release profile takes a long time to build so we can use this profile during development to save time
# cargo build --profile release-nonlto
[profile.release-nonlto]
codegen-units = 16
debug-assertions = false
incremental = false
inherits = "release"
lto = false
opt-level = 3
overflow-checks = false
rpath = false
strip = false            # Retain debug info for flamegraphs

[profile.ci]
inherits = "dev"
incremental = false

# ci turns off debug info, etc. for dependencies to allow for smaller binaries making caching more effective
[profile.ci.package."*"]
debug = false
debug-assertions = false
strip = "debuginfo"
incremental = false

# release inherited profile keeping debug information and symbols
# for mem/cpu profiling
[profile.profiling]
inherits = "release"
debug = true
strip = false

# release-non-lto inherited profile keeping debug information and symbols for mem/cpu profiling. "Full" release builds
# tend to violate the resource constraints of the GitHub runners.
[profile.profiling-nonlto]
inherits = "release-nonlto"
debug = true
strip = false

[workspace.lints.clippy]
# Detects large stack-allocated futures that may cause stack overflow crashes (see threshold in clippy.toml)
large_futures = "warn"
used_underscore_binding = "warn"
or_fun_call = "warn"
unnecessary_lazy_evaluations = "warn"
uninlined_format_args = "warn"
clone_on_ref_ptr = "warn"
await_holding_lock = "warn"
await_holding_refcell_ref = "warn"
disallowed_types = "warn"
disallowed_methods = "warn"

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
  'cfg(datafusion_coop, values("tokio", "tokio_fallback", "per_stream"))',
  "cfg(tarpaulin)",
  "cfg(tarpaulin_include)",
] }
unused_qualifications = "deny"
