name: Deploy to Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: tuw-runner
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify
        working-directory: misc/pages

      - name: Deploy to Codeberg Pages
        uses: https://codeberg.org/git-pages/action@v2
        with:
          site: https://tschwarzinger.codeberg.page/rdf-fusion/
          token: ${{ forge.token }}
          source: misc/pages/public/
