name: Web

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: tuw-runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: https://github.com/actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: misc/pages/package-lock.json

      - name: Install Frontend Dependencies
        run: npm ci
        working-directory: misc/pages

      - name: Lint HTML & CSS
        run: npx --yes prettier@3 --check "**/*.{css,html}"

      - name: Lint JS & Svelte
        run: npm run lint
        working-directory: misc/pages
